### PR TITLE
Do not allow consecutive blank lines

### PR DESCRIPTION
**Pull request by brandonduff**
- This matches our Ruby linting.
- Came out of comments from this PR: https://github.com/mavenlink/mavenlink/pull/8982

### CODE REVIEW

**Comment by brandonduff** [comment]
What is our strategy for versioning? I figure this PR should involve bumping the version. I just wasn't sure what to bump to.

**Comment by ahuth** [comment]
I'd recommend bumping the minor version, so to `2.1.0`.

**Comment by ahuth** [comment]
This looks good. Let's wait until next week to get some more feedback on this rule. There's a bunch of people OOO today, and I don't want to add rules without getting some more feedback/consensus.

**Comment by brandonduff** [comment]
@naganowl I can bring it up as an interesting on Monday. Who has the ability to publish a new version? I'm not sure if I have an npm login or what my credentials are.

**Comment by naganowl** [comment]
@brandonduff try `npm publish` to see if you already have access. Otherwise, @ahuth or @racerpeter probably can help you there.

**Comment by ahuth** [comment]
I can publish it once this is in

**Comment by naganowl** [comment]
Yeah there's no problem having this merged and then published.

Alternatively, @ahuth can just checkout this branch and just publish.

**Comment by brandonduff** [comment]
Sweet. I'll go ahead and merge. Let me know when the newest version is published and I can open a PR in Mavenlink that bumps it fixes any errors.

**Comment by ahuth** [comment]
It is published @brandonduff

**Pull request merged**
